### ISSUE TITLE
L1 Mastering Font checklist

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/updock#3]
### L1 Mastering Font checklist

**Diacritics**
- [x] Inspect the font and choose the best version of the diacritics (in terms of balance, weight, size, contrast) and move them to comb mark.
- [x] Adjust left and right sidebearings of all the comb marks to 0 (so that they are easy to edit)
- [x] Ensure the diacritics consistency with the font characteristics + among related marks, [see issue of reference](https://github.com/googlefonts/italianno/issues/6).
- [x] Work on the selected diacritics to ensure the balance among all marks (contrast, weight, size, stroke or others)
- [x] Adjust position, weight, or outlines of the diacritics if needed, without changing the design of them, and using glyphs app locked guidelines.
- [x] Decomposed transformed components, review proportions ensuring round coordinates.
- [x] Test the comb marks by inspecting all of them in context (right-click and choose all glyphs using this component).
- [x] Inspect and balance the below marks (size, weight, balance) e.g. `ogonek` `cedilla` to avoid huge marks
- [x] Create [Catalan Punt Volat ](https://glyphsapp.com/learn/localize-your-font-catalan-punt-volat)
- [x] Delete the legacy marks and add them back so they are made from comb marks.
- [x] Create comb.case marks by making them less tall and less narrow while keeping them at the same weight (preferable at the height they are intended to use, to be able to inspect them in their context)
- [x] Create the Vietnamese diacritics by using a specific anchor (e.g. topviet) so that composite glyphs could be automatically updated
- [x] Make composite glyphs for the entire font.
- [x] Review and adjust the anchors position.

**Glyphs & Outlines**
- [x] Create the missing glyphs to cover the Latin Core and Plus GF encodings if they are easy to go cases. Otherwise, please report them to the designer in the Design Issue.
- [x] Inspect all the included glyphs has the Upper and Lowercase. 
- [x] Ensure the above item by inspecting there are no glyphs with double encodings (Uppers + lowercase)
- [x] Decompose the Currency symbols to avoid inconsistencies when the current components are changed (e.g. hyphen)
- [x] Check, solve or report as needed the currency symbols size, weight, consistency with the font.  
- [x] Inspect current kerning and delete the pairs that are not needed or not ideal (e.g. some numerals and quotes)
- [x] Check kerning and spacing by using the .txt files. Fix any kerning and spacing critical cases (covering the most common kerning pairs).
- [x] After the revision to numerals spacing/kerning generate again the `.lf` using the main version (e.g. zero=zero.f) 
- [x] Check the spacing of terminal forms to avoid crashes or collisions. [Issue of reference](https://github.com/googlefonts/comforter/issues/7)
- [x] Check `@` `¿?` `¡!` `””` `«»` and overall punctuation position and spacing is ok. Use key sidebearings + kerning groups to ensure consistency. Include `//` kerning.
- [x] Ensure there are no punctuation with components at the same position (e.g. ellipsis)
- [x] Run the automatic Glyphsapp command: `Resolve all metrics` to update the metrics in the entire font.
- [x] Check everything once again by going glyph by glyph.
- [x] Inspect the ligatures coherence with the font (shape, spacing/kerning)
- [x] Inspect/solve `fraction` consistency with the fractions. Adjust its sidebearings (negative).

**OT Features**
- [x] Check OpenType features and see if all listed are valid. E.g. if `.fina` glyphs are actually ending shapes or SS are not repeated under different names.
- [x] Create Lookup for positional alternates for `fina` and `init` cases. [Luxurious as reference case](https://github.com/googlefonts/luxurious/tree/master/sources)
- [x] All the features/classes that could be done automatically to be done in that way, e.g. `All Letters` 
- [x] Inspect if Stylistic Sets have the right suffix (ss01 instead of .001 etc) glyphs and generate the automatic OpenType code.
- [x] Check if there any Stylistic Set should be treated as any other feature, e.g. `SmallCaps` or `osf`.
- [x] Check the OpenType code has any error. Hit the `update` & `compile` buttons to check everything is working well.

**Testing changes**
- [ ] Inspect the font created by the CI GHA to check production errors. If the action isn't included yet in the repo, export and test the font using Glyphs.
- [ ] Check the before and after font using `gen-html diff` if needed (for update font cases)
- [ ] Check the font on `gen-html proof` to see if it's working well on web. Use the `--imgs` flag to produce images.
- [ ] Commit and make PR using images.

**Comment by vv-monsalve** [comment]
@Fonthausen Updock (and Whisper) had similar `topviet` marks issues

- Anchor in base glyph (e.g. `circumflex`) but not in combining mark (e.g. `acute`)
- Stacked diacritics not built automatically 
- Therefore no auto-updating after changes
- Outlines still with no good on-curve points e.g. broken smooth connection

Please remember to include these fixes for pending projects.

<img width="809" alt="Screen Shot 2022-03-24 at 18 26 54" src="https://user-images.githubusercontent.com/48698976/160026440-86e27ab3-2343-4f4a-95ee-6bc5711ac2a5.png">
